"""Deploy and control a GStreamer RTSP server on the remote camera device.

Instead of SSH-launching ``gst-launch-1.0`` per camera and discovering the
process by diffing ``pgrep`` output, this runs one ``gst-rtsp-server``
process on the device that serves every camera as an RTSP mount point
(``rtsp://device:8554/eo``, ``rtsp://device:8554/ir``, ...). The ground
station then gets connection negotiation, clean reconnects, and multiple
simultaneous clients for free, and teardown is a single ``pkill`` of a
known script name.

Device requirements: GStreamer with the RTSP server library and PyGObject —
on Debian-family images ``python3-gi`` and ``gir1.2-gst-rtsp-server-1.0``.
Verify once with ``python3 -c "import gi; gi.require_version('GstRtspServer', '1.0')"``
on the device.

This module has not been exercised against RB5 hardware; validate on the
bench before relying on it in the field.
"""

import logging
import os
import tempfile
import time

from image_processing.connection.sftp import SFTPController
from image_processing.connection.ssh import SSH_Controller

LOGGER = logging.getLogger(__name__)

_SERVER_SCRIPT_TEMPLATE = '''#!/usr/bin/env python3
"""UHDT RTSP camera server (generated by image_processing.camera.backends.rtsp)."""
import gi
gi.require_version("Gst", "1.0")
gi.require_version("GstRtspServer", "1.0")
from gi.repository import Gst, GstRtspServer, GLib

Gst.init(None)

server = GstRtspServer.RTSPServer()
server.set_service("{port}")
mounts = server.get_mount_points()

STREAMS = {streams!r}

for mount, launch in STREAMS.items():
    factory = GstRtspServer.RTSPMediaFactory()
    factory.set_launch("( " + launch + " )")
    factory.set_shared(True)
    mounts.add_factory("/" + mount, factory)

server.attach(None)
print("RTSP server on port {port}, mounts:", ", ".join("/" + m for m in STREAMS))
GLib.MainLoop().run()
'''


class RTSPCameraServer:
    """
    Manage a gst-rtsp-server process on the remote camera device.

    Typical use::

        server = RTSPCameraServer(host, username, password)
        server.addStream("eo", eo_launch_chain)   # ends in rtph264pay name=pay0
        server.addStream("ir", ir_launch_chain)
        server.deploy()
        server.start()
        ...
        server.stop()

    Parameters
    ----------
    host : str
        IP address of the remote device.
    username, password : str
        SSH/SFTP credentials.
    port : int, optional
        RTSP service port (default 8554).
    remote_script_path : str, optional
        Where the generated server script is placed on the device.
    """

    def __init__(
        self,
        host: str,
        username: str,
        password: str,
        port: int = 8554,
        remote_script_path: str = "/tmp/uhdt_rtsp_server.py",
    ):
        self.host = host
        self.port = port
        self.remote_script_path = remote_script_path
        self.streams: dict[str, str] = {}
        self.ssh = SSH_Controller(host, username, password)
        self.sftp = SFTPController(host, username, password)
        self.running = False

    def addStream(self, mount: str, launch_chain: str) -> None:
        """
        Register a camera under an RTSP mount point.

        Parameters
        ----------
        mount : str
            Mount name; the stream is served at ``rtsp://host:port/<mount>``.
        launch_chain : str
            gst-launch chain from source through encoder, ending in
            ``rtph264pay name=pay0 pt=96`` (RTSP media factory convention).
        """
        if "rtph264pay" not in launch_chain or "name=pay0" not in launch_chain:
            raise ValueError("launch_chain must end in 'rtph264pay name=pay0 pt=96'")
        self.streams[mount] = launch_chain

    def streamUri(self, mount: str) -> str:
        """Return the RTSP URI for a registered mount."""
        return f"rtsp://{self.host}:{self.port}/{mount}"

    def generateScript(self) -> str:
        """Return the server script text for the registered streams."""
        if not self.streams:
            raise RuntimeError("No streams registered; call addStream first")
        return _SERVER_SCRIPT_TEMPLATE.format(port=self.port, streams=self.streams)

    def deploy(self) -> None:
        """Upload the generated server script to the device over SFTP."""
        script = self.generateScript()
        with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False) as f:
            f.write(script)
            local_path = f.name
        try:
            self.sftp.connect()
            self.sftp.uploadFile(local_path, self.remote_script_path)
            self.sftp.disconnect()
        finally:
            os.unlink(local_path)
        LOGGER.info("Deployed RTSP server script to %s:%s", self.host, self.remote_script_path)

    def isRunning(self) -> bool:
        """Return True if the server process exists on the device."""
        if not self.ssh.is_connected:
            return False
        cmd_output = self.ssh.run_cmd(f"pgrep -f {os.path.basename(self.remote_script_path)}")
        if cmd_output is None:
            return False
        return len(self.ssh.parse_cmd_output(cmd_output)) > 0

    def start(self, startup_timeout: float = 5.0) -> None:
        """
        Stop any previous instance and launch the server in the background.

        Polls for the server process for up to ``startup_timeout`` seconds
        and logs an error (with the likely missing device dependencies) if
        it did not stay up.
        """
        self.ssh.connect()
        self.ssh.run_cmd(f"pkill -f {os.path.basename(self.remote_script_path)}")
        self.ssh.run_cmd(f"python3 {self.remote_script_path}", background=True)

        deadline = time.monotonic() + startup_timeout
        while time.monotonic() < deadline:
            if self.isRunning():
                self.running = True
                LOGGER.info("Started RTSP server at rtsp://%s:%d/", self.host, self.port)
                return
            time.sleep(0.5)

        LOGGER.error(
            "RTSP server did not start on %s. Check that the device has "
            "python3-gi and gir1.2-gst-rtsp-server-1.0 installed "
            "(see image_processing/camera/backends/README.md), and inspect "
            "nohup.out on the device for the traceback.",
            self.host,
        )

    def stop(self) -> None:
        """Terminate the server process on the device."""
        if self.ssh.is_connected:
            self.ssh.run_cmd(f"pkill -f {os.path.basename(self.remote_script_path)}")
            self.ssh.disconnect()
        self.running = False
        LOGGER.info("Stopped RTSP server on %s", self.host)
